### PR TITLE
fixed date string unit test

### PR DESCRIPTION
**Pull request by JesterXL**
Fixed your 2 unit tests that were failing on my box. They were looking for verbose unit tests, changed to simple.

### CODE REVIEW

**Comment by JesterXL** [comment]
Weird, the Travis CI build failed... is this browser specific behavior? Lemme update this PR tomorrow with some more unit tests and we'll see.

**Comment by mikemaccana** [comment]
Thanks Jesse! Super busy day here (my company is on the front page of HN and it's our busiest day ever) but I wanted to say I;m glad for the contribution and will check this out shortly.

**Comment by mikemaccana** [comment]
Tests are run in v8, so maybe it's JS engine specific. Still it looks like it's a bug if it isn't passing on some browsers. Going to investigate (if you don't get there first!)

**Comment by JesterXL** [comment]
No worries, I'm the one who submitted the PR, let me do the due diligence first and you sound uber-busy.

**Comment by JesterXL** [comment]
K, so here's my first clue. If I go:

`new Date().toLocaleDateString("en-GB", {timeZone:'UTC'})`

In Chrome, Firefox, and Safari, check out Safari:

Chrome: `16/05/2015`
Firefox: `16/05/2015`
Safari: `May 16, 2015`

lulz.

I've struggled all morning to get karma up and running to prevent this from happening in the future, but a few key packages have been updated in browserify/karma/chai, so... nothing works, lol.

I think we shouldn't test for locale, since that's more for [users to read and customize](http://stackoverflow.com/questions/22719346/tolocaledatestring-is-not-returning-dd-mm-yyyy-format), but rather, if the actual date itself has changed. Something like:
```javascript
test('correctly converts a number to a period in weeks before a set date', function(){
    var someDate = new Date('Thu Jun 06 2013 22:44:05 GMT+0100 (UTC)');
    var timezoneOffset = someDate.getTimezoneOffset();
    var targetDate = new Date('Thu May 16 2013 22:44:05 GMT+0100 (UTC)')
    assert.equal((3).avweeks().avbefore(someDate).getDate(), targetDate.getDate());
  });
```

What do you think?

**Comment by JesterXL** [comment]
Boom, Travis digs it!

**Comment by mikemaccana** [comment]
Thanks @JesterXL!

**Pull request merged**
